// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: steammessages_remoteclient_discovery.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteClientBroadcastHeader : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"client_id")]
    public ulong ClientId
    {
        get { return __pbn__ClientId.GetValueOrDefault(); }
        set { __pbn__ClientId = value; }
    }
    public bool ShouldSerializeClientId() => __pbn__ClientId != null;
    public void ResetClientId() => __pbn__ClientId = null;
    private ulong? __pbn__ClientId;

    [global::ProtoBuf.ProtoMember(2, Name = @"msg_type")]
    [global::System.ComponentModel.DefaultValue(ERemoteClientBroadcastMsg.kERemoteClientBroadcastMsgDiscovery)]
    public ERemoteClientBroadcastMsg MsgType
    {
        get { return __pbn__MsgType ?? ERemoteClientBroadcastMsg.kERemoteClientBroadcastMsgDiscovery; }
        set { __pbn__MsgType = value; }
    }
    public bool ShouldSerializeMsgType() => __pbn__MsgType != null;
    public void ResetMsgType() => __pbn__MsgType = null;
    private ERemoteClientBroadcastMsg? __pbn__MsgType;

    [global::ProtoBuf.ProtoMember(3, Name = @"instance_id")]
    public ulong InstanceId
    {
        get { return __pbn__InstanceId.GetValueOrDefault(); }
        set { __pbn__InstanceId = value; }
    }
    public bool ShouldSerializeInstanceId() => __pbn__InstanceId != null;
    public void ResetInstanceId() => __pbn__InstanceId = null;
    private ulong? __pbn__InstanceId;

    [global::ProtoBuf.ProtoMember(4, Name = @"device_id")]
    public ulong DeviceId
    {
        get { return __pbn__DeviceId.GetValueOrDefault(); }
        set { __pbn__DeviceId = value; }
    }
    public bool ShouldSerializeDeviceId() => __pbn__DeviceId != null;
    public void ResetDeviceId() => __pbn__DeviceId = null;
    private ulong? __pbn__DeviceId;

    [global::ProtoBuf.ProtoMember(5, Name = @"device_token")]
    public byte[] DeviceToken
    {
        get { return __pbn__DeviceToken; }
        set { __pbn__DeviceToken = value; }
    }
    public bool ShouldSerializeDeviceToken() => __pbn__DeviceToken != null;
    public void ResetDeviceToken() => __pbn__DeviceToken = null;
    private byte[] __pbn__DeviceToken;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteClientBroadcastStatus : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"version")]
    public int Version
    {
        get { return __pbn__Version.GetValueOrDefault(); }
        set { __pbn__Version = value; }
    }
    public bool ShouldSerializeVersion() => __pbn__Version != null;
    public void ResetVersion() => __pbn__Version = null;
    private int? __pbn__Version;

    [global::ProtoBuf.ProtoMember(2, Name = @"min_version")]
    public int MinVersion
    {
        get { return __pbn__MinVersion.GetValueOrDefault(); }
        set { __pbn__MinVersion = value; }
    }
    public bool ShouldSerializeMinVersion() => __pbn__MinVersion != null;
    public void ResetMinVersion() => __pbn__MinVersion = null;
    private int? __pbn__MinVersion;

    [global::ProtoBuf.ProtoMember(3, Name = @"connect_port")]
    public uint ConnectPort
    {
        get { return __pbn__ConnectPort.GetValueOrDefault(); }
        set { __pbn__ConnectPort = value; }
    }
    public bool ShouldSerializeConnectPort() => __pbn__ConnectPort != null;
    public void ResetConnectPort() => __pbn__ConnectPort = null;
    private uint? __pbn__ConnectPort;

    [global::ProtoBuf.ProtoMember(4, Name = @"hostname")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Hostname
    {
        get { return __pbn__Hostname ?? ""; }
        set { __pbn__Hostname = value; }
    }
    public bool ShouldSerializeHostname() => __pbn__Hostname != null;
    public void ResetHostname() => __pbn__Hostname = null;
    private string __pbn__Hostname;

    [global::ProtoBuf.ProtoMember(6, Name = @"enabled_services")]
    public uint EnabledServices
    {
        get { return __pbn__EnabledServices.GetValueOrDefault(); }
        set { __pbn__EnabledServices = value; }
    }
    public bool ShouldSerializeEnabledServices() => __pbn__EnabledServices != null;
    public void ResetEnabledServices() => __pbn__EnabledServices = null;
    private uint? __pbn__EnabledServices;

    [global::ProtoBuf.ProtoMember(7, Name = @"ostype")]
    [global::System.ComponentModel.DefaultValue(0)]
    public int Ostype
    {
        get { return __pbn__Ostype ?? 0; }
        set { __pbn__Ostype = value; }
    }
    public bool ShouldSerializeOstype() => __pbn__Ostype != null;
    public void ResetOstype() => __pbn__Ostype = null;
    private int? __pbn__Ostype;

    [global::ProtoBuf.ProtoMember(8, Name = @"is64bit")]
    public bool Is64bit
    {
        get { return __pbn__Is64bit.GetValueOrDefault(); }
        set { __pbn__Is64bit = value; }
    }
    public bool ShouldSerializeIs64bit() => __pbn__Is64bit != null;
    public void ResetIs64bit() => __pbn__Is64bit = null;
    private bool? __pbn__Is64bit;

    [global::ProtoBuf.ProtoMember(9, Name = @"users")]
    public global::System.Collections.Generic.List<User> Users { get; } = new global::System.Collections.Generic.List<User>();

    [global::ProtoBuf.ProtoMember(11, Name = @"euniverse")]
    public int Euniverse
    {
        get { return __pbn__Euniverse.GetValueOrDefault(); }
        set { __pbn__Euniverse = value; }
    }
    public bool ShouldSerializeEuniverse() => __pbn__Euniverse != null;
    public void ResetEuniverse() => __pbn__Euniverse = null;
    private int? __pbn__Euniverse;

    [global::ProtoBuf.ProtoMember(12, Name = @"timestamp")]
    public uint Timestamp
    {
        get { return __pbn__Timestamp.GetValueOrDefault(); }
        set { __pbn__Timestamp = value; }
    }
    public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
    public void ResetTimestamp() => __pbn__Timestamp = null;
    private uint? __pbn__Timestamp;

    [global::ProtoBuf.ProtoMember(13, Name = @"screen_locked")]
    public bool ScreenLocked
    {
        get { return __pbn__ScreenLocked.GetValueOrDefault(); }
        set { __pbn__ScreenLocked = value; }
    }
    public bool ShouldSerializeScreenLocked() => __pbn__ScreenLocked != null;
    public void ResetScreenLocked() => __pbn__ScreenLocked = null;
    private bool? __pbn__ScreenLocked;

    [global::ProtoBuf.ProtoMember(14, Name = @"games_running")]
    public bool GamesRunning
    {
        get { return __pbn__GamesRunning.GetValueOrDefault(); }
        set { __pbn__GamesRunning = value; }
    }
    public bool ShouldSerializeGamesRunning() => __pbn__GamesRunning != null;
    public void ResetGamesRunning() => __pbn__GamesRunning = null;
    private bool? __pbn__GamesRunning;

    [global::ProtoBuf.ProtoMember(15, Name = @"mac_addresses")]
    public global::System.Collections.Generic.List<string> MacAddresses { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(16, Name = @"download_lan_peer_group")]
    public uint DownloadLanPeerGroup
    {
        get { return __pbn__DownloadLanPeerGroup.GetValueOrDefault(); }
        set { __pbn__DownloadLanPeerGroup = value; }
    }
    public bool ShouldSerializeDownloadLanPeerGroup() => __pbn__DownloadLanPeerGroup != null;
    public void ResetDownloadLanPeerGroup() => __pbn__DownloadLanPeerGroup = null;
    private uint? __pbn__DownloadLanPeerGroup;

    [global::ProtoBuf.ProtoMember(17, Name = @"broadcasting_active")]
    public bool BroadcastingActive
    {
        get { return __pbn__BroadcastingActive.GetValueOrDefault(); }
        set { __pbn__BroadcastingActive = value; }
    }
    public bool ShouldSerializeBroadcastingActive() => __pbn__BroadcastingActive != null;
    public void ResetBroadcastingActive() => __pbn__BroadcastingActive = null;
    private bool? __pbn__BroadcastingActive;

    [global::ProtoBuf.ProtoMember(18, Name = @"vr_active")]
    public bool VrActive
    {
        get { return __pbn__VrActive.GetValueOrDefault(); }
        set { __pbn__VrActive = value; }
    }
    public bool ShouldSerializeVrActive() => __pbn__VrActive != null;
    public void ResetVrActive() => __pbn__VrActive = null;
    private bool? __pbn__VrActive;

    [global::ProtoBuf.ProtoMember(19, Name = @"content_cache_port")]
    public uint ContentCachePort
    {
        get { return __pbn__ContentCachePort.GetValueOrDefault(); }
        set { __pbn__ContentCachePort = value; }
    }
    public bool ShouldSerializeContentCachePort() => __pbn__ContentCachePort != null;
    public void ResetContentCachePort() => __pbn__ContentCachePort = null;
    private uint? __pbn__ContentCachePort;

    [global::ProtoBuf.ProtoMember(20, Name = @"ip_addresses")]
    public global::System.Collections.Generic.List<string> IpAddresses { get; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(21, Name = @"public_ip_address")]
    [global::System.ComponentModel.DefaultValue("")]
    public string PublicIpAddress
    {
        get { return __pbn__PublicIpAddress ?? ""; }
        set { __pbn__PublicIpAddress = value; }
    }
    public bool ShouldSerializePublicIpAddress() => __pbn__PublicIpAddress != null;
    public void ResetPublicIpAddress() => __pbn__PublicIpAddress = null;
    private string __pbn__PublicIpAddress;

    [global::ProtoBuf.ProtoMember(22, Name = @"remoteplay_active")]
    public bool RemoteplayActive
    {
        get { return __pbn__RemoteplayActive.GetValueOrDefault(); }
        set { __pbn__RemoteplayActive = value; }
    }
    public bool ShouldSerializeRemoteplayActive() => __pbn__RemoteplayActive != null;
    public void ResetRemoteplayActive() => __pbn__RemoteplayActive = null;
    private bool? __pbn__RemoteplayActive;

    [global::ProtoBuf.ProtoContract()]
    public partial class User : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"steamid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Steamid
        {
            get { return __pbn__Steamid.GetValueOrDefault(); }
            set { __pbn__Steamid = value; }
        }
        public bool ShouldSerializeSteamid() => __pbn__Steamid != null;
        public void ResetSteamid() => __pbn__Steamid = null;
        private ulong? __pbn__Steamid;

        [global::ProtoBuf.ProtoMember(2, Name = @"auth_key_id")]
        public uint AuthKeyId
        {
            get { return __pbn__AuthKeyId.GetValueOrDefault(); }
            set { __pbn__AuthKeyId = value; }
        }
        public bool ShouldSerializeAuthKeyId() => __pbn__AuthKeyId != null;
        public void ResetAuthKeyId() => __pbn__AuthKeyId = null;
        private uint? __pbn__AuthKeyId;

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteClientBroadcastDiscovery : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"seq_num")]
    public uint SeqNum
    {
        get { return __pbn__SeqNum.GetValueOrDefault(); }
        set { __pbn__SeqNum = value; }
    }
    public bool ShouldSerializeSeqNum() => __pbn__SeqNum != null;
    public void ResetSeqNum() => __pbn__SeqNum = null;
    private uint? __pbn__SeqNum;

    [global::ProtoBuf.ProtoMember(2, Name = @"client_ids")]
    public ulong[] ClientIds { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteClientBroadcastClientIDDeconflict : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(2, Name = @"client_ids")]
    public ulong[] ClientIds { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceAuthorizationRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"device_token", IsRequired = true)]
    public byte[] DeviceToken { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"device_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public string DeviceName
    {
        get { return __pbn__DeviceName ?? ""; }
        set { __pbn__DeviceName = value; }
    }
    public bool ShouldSerializeDeviceName() => __pbn__DeviceName != null;
    public void ResetDeviceName() => __pbn__DeviceName = null;
    private string __pbn__DeviceName;

    [global::ProtoBuf.ProtoMember(3, Name = @"encrypted_request", IsRequired = true)]
    public byte[] EncryptedRequest { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"CKeyEscrow_Ticket")]
    public partial class CKeyEscrowTicket : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"password")]
        public byte[] Password
        {
            get { return __pbn__Password; }
            set { __pbn__Password = value; }
        }
        public bool ShouldSerializePassword() => __pbn__Password != null;
        public void ResetPassword() => __pbn__Password = null;
        private byte[] __pbn__Password;

        [global::ProtoBuf.ProtoMember(2, Name = @"identifier")]
        public ulong Identifier
        {
            get { return __pbn__Identifier.GetValueOrDefault(); }
            set { __pbn__Identifier = value; }
        }
        public bool ShouldSerializeIdentifier() => __pbn__Identifier != null;
        public void ResetIdentifier() => __pbn__Identifier = null;
        private ulong? __pbn__Identifier;

        [global::ProtoBuf.ProtoMember(3, Name = @"payload")]
        public byte[] Payload
        {
            get { return __pbn__Payload; }
            set { __pbn__Payload = value; }
        }
        public bool ShouldSerializePayload() => __pbn__Payload != null;
        public void ResetPayload() => __pbn__Payload = null;
        private byte[] __pbn__Payload;

        [global::ProtoBuf.ProtoMember(4, Name = @"timestamp")]
        public uint Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
        public void ResetTimestamp() => __pbn__Timestamp = null;
        private uint? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(5, Name = @"usage")]
        [global::System.ComponentModel.DefaultValue(CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage.kEKeyEscrowUsageStreamingDevice)]
        public CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage Usage
        {
            get { return __pbn__Usage ?? CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage.kEKeyEscrowUsageStreamingDevice; }
            set { __pbn__Usage = value; }
        }
        public bool ShouldSerializeUsage() => __pbn__Usage != null;
        public void ResetUsage() => __pbn__Usage = null;
        private CMsgRemoteDeviceAuthorizationRequest.EKeyEscrowUsage? __pbn__Usage;

        [global::ProtoBuf.ProtoMember(6, Name = @"device_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceName
        {
            get { return __pbn__DeviceName ?? ""; }
            set { __pbn__DeviceName = value; }
        }
        public bool ShouldSerializeDeviceName() => __pbn__DeviceName != null;
        public void ResetDeviceName() => __pbn__DeviceName = null;
        private string __pbn__DeviceName;

        [global::ProtoBuf.ProtoMember(7, Name = @"device_model")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceModel
        {
            get { return __pbn__DeviceModel ?? ""; }
            set { __pbn__DeviceModel = value; }
        }
        public bool ShouldSerializeDeviceModel() => __pbn__DeviceModel != null;
        public void ResetDeviceModel() => __pbn__DeviceModel = null;
        private string __pbn__DeviceModel;

        [global::ProtoBuf.ProtoMember(8, Name = @"device_serial")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DeviceSerial
        {
            get { return __pbn__DeviceSerial ?? ""; }
            set { __pbn__DeviceSerial = value; }
        }
        public bool ShouldSerializeDeviceSerial() => __pbn__DeviceSerial != null;
        public void ResetDeviceSerial() => __pbn__DeviceSerial = null;
        private string __pbn__DeviceSerial;

        [global::ProtoBuf.ProtoMember(9, Name = @"device_provisioning_id")]
        public uint DeviceProvisioningId
        {
            get { return __pbn__DeviceProvisioningId.GetValueOrDefault(); }
            set { __pbn__DeviceProvisioningId = value; }
        }
        public bool ShouldSerializeDeviceProvisioningId() => __pbn__DeviceProvisioningId != null;
        public void ResetDeviceProvisioningId() => __pbn__DeviceProvisioningId = null;
        private uint? __pbn__DeviceProvisioningId;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EKeyEscrowUsage
    {
        [global::ProtoBuf.ProtoEnum(Name = @"k_EKeyEscrowUsageStreamingDevice")]
        kEKeyEscrowUsageStreamingDevice = 0,
    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceAuthorizationCancelRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceAuthorizationResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"result", IsRequired = true)]
    public ERemoteDeviceAuthorizationResult Result { get; set; } = ERemoteDeviceAuthorizationResult.kERemoteDeviceAuthorizationSuccess;

    [global::ProtoBuf.ProtoMember(2, Name = @"steamid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong Steamid
    {
        get { return __pbn__Steamid.GetValueOrDefault(); }
        set { __pbn__Steamid = value; }
    }
    public bool ShouldSerializeSteamid() => __pbn__Steamid != null;
    public void ResetSteamid() => __pbn__Steamid = null;
    private ulong? __pbn__Steamid;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceStreamingRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"request_id", IsRequired = true)]
    public uint RequestId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"maximum_resolution_x")]
    public int MaximumResolutionX
    {
        get { return __pbn__MaximumResolutionX.GetValueOrDefault(); }
        set { __pbn__MaximumResolutionX = value; }
    }
    public bool ShouldSerializeMaximumResolutionX() => __pbn__MaximumResolutionX != null;
    public void ResetMaximumResolutionX() => __pbn__MaximumResolutionX = null;
    private int? __pbn__MaximumResolutionX;

    [global::ProtoBuf.ProtoMember(3, Name = @"maximum_resolution_y")]
    public int MaximumResolutionY
    {
        get { return __pbn__MaximumResolutionY.GetValueOrDefault(); }
        set { __pbn__MaximumResolutionY = value; }
    }
    public bool ShouldSerializeMaximumResolutionY() => __pbn__MaximumResolutionY != null;
    public void ResetMaximumResolutionY() => __pbn__MaximumResolutionY = null;
    private int? __pbn__MaximumResolutionY;

    [global::ProtoBuf.ProtoMember(4, Name = @"audio_channel_count")]
    [global::System.ComponentModel.DefaultValue(2)]
    public int AudioChannelCount
    {
        get { return __pbn__AudioChannelCount ?? 2; }
        set { __pbn__AudioChannelCount = value; }
    }
    public bool ShouldSerializeAudioChannelCount() => __pbn__AudioChannelCount != null;
    public void ResetAudioChannelCount() => __pbn__AudioChannelCount = null;
    private int? __pbn__AudioChannelCount;

    [global::ProtoBuf.ProtoMember(5, Name = @"device_version")]
    [global::System.ComponentModel.DefaultValue("")]
    public string DeviceVersion
    {
        get { return __pbn__DeviceVersion ?? ""; }
        set { __pbn__DeviceVersion = value; }
    }
    public bool ShouldSerializeDeviceVersion() => __pbn__DeviceVersion != null;
    public void ResetDeviceVersion() => __pbn__DeviceVersion = null;
    private string __pbn__DeviceVersion;

    [global::ProtoBuf.ProtoMember(6, Name = @"stream_desktop")]
    public bool StreamDesktop
    {
        get { return __pbn__StreamDesktop.GetValueOrDefault(); }
        set { __pbn__StreamDesktop = value; }
    }
    public bool ShouldSerializeStreamDesktop() => __pbn__StreamDesktop != null;
    public void ResetStreamDesktop() => __pbn__StreamDesktop = null;
    private bool? __pbn__StreamDesktop;

    [global::ProtoBuf.ProtoMember(7, Name = @"device_token")]
    public byte[] DeviceToken
    {
        get { return __pbn__DeviceToken; }
        set { __pbn__DeviceToken = value; }
    }
    public bool ShouldSerializeDeviceToken() => __pbn__DeviceToken != null;
    public void ResetDeviceToken() => __pbn__DeviceToken = null;
    private byte[] __pbn__DeviceToken;

    [global::ProtoBuf.ProtoMember(8, Name = @"pin")]
    public byte[] Pin
    {
        get { return __pbn__Pin; }
        set { __pbn__Pin = value; }
    }
    public bool ShouldSerializePin() => __pbn__Pin != null;
    public void ResetPin() => __pbn__Pin = null;
    private byte[] __pbn__Pin;

    [global::ProtoBuf.ProtoMember(9, Name = @"enable_video_streaming")]
    [global::System.ComponentModel.DefaultValue(true)]
    public bool EnableVideoStreaming
    {
        get { return __pbn__EnableVideoStreaming ?? true; }
        set { __pbn__EnableVideoStreaming = value; }
    }
    public bool ShouldSerializeEnableVideoStreaming() => __pbn__EnableVideoStreaming != null;
    public void ResetEnableVideoStreaming() => __pbn__EnableVideoStreaming = null;
    private bool? __pbn__EnableVideoStreaming;

    [global::ProtoBuf.ProtoMember(10, Name = @"enable_audio_streaming")]
    [global::System.ComponentModel.DefaultValue(true)]
    public bool EnableAudioStreaming
    {
        get { return __pbn__EnableAudioStreaming ?? true; }
        set { __pbn__EnableAudioStreaming = value; }
    }
    public bool ShouldSerializeEnableAudioStreaming() => __pbn__EnableAudioStreaming != null;
    public void ResetEnableAudioStreaming() => __pbn__EnableAudioStreaming = null;
    private bool? __pbn__EnableAudioStreaming;

    [global::ProtoBuf.ProtoMember(11, Name = @"enable_input_streaming")]
    [global::System.ComponentModel.DefaultValue(true)]
    public bool EnableInputStreaming
    {
        get { return __pbn__EnableInputStreaming ?? true; }
        set { __pbn__EnableInputStreaming = value; }
    }
    public bool ShouldSerializeEnableInputStreaming() => __pbn__EnableInputStreaming != null;
    public void ResetEnableInputStreaming() => __pbn__EnableInputStreaming = null;
    private bool? __pbn__EnableInputStreaming;

    [global::ProtoBuf.ProtoMember(12, Name = @"network_test")]
    public bool NetworkTest
    {
        get { return __pbn__NetworkTest.GetValueOrDefault(); }
        set { __pbn__NetworkTest = value; }
    }
    public bool ShouldSerializeNetworkTest() => __pbn__NetworkTest != null;
    public void ResetNetworkTest() => __pbn__NetworkTest = null;
    private bool? __pbn__NetworkTest;

    [global::ProtoBuf.ProtoMember(13, Name = @"client_id")]
    public ulong ClientId
    {
        get { return __pbn__ClientId.GetValueOrDefault(); }
        set { __pbn__ClientId = value; }
    }
    public bool ShouldSerializeClientId() => __pbn__ClientId != null;
    public void ResetClientId() => __pbn__ClientId = null;
    private ulong? __pbn__ClientId;

    [global::ProtoBuf.ProtoMember(14, Name = @"supported_transport")]
    public global::System.Collections.Generic.List<EStreamTransport> SupportedTransports { get; } = new global::System.Collections.Generic.List<EStreamTransport>();

    [global::ProtoBuf.ProtoMember(15, Name = @"restricted")]
    public bool Restricted
    {
        get { return __pbn__Restricted.GetValueOrDefault(); }
        set { __pbn__Restricted = value; }
    }
    public bool ShouldSerializeRestricted() => __pbn__Restricted != null;
    public void ResetRestricted() => __pbn__Restricted = null;
    private bool? __pbn__Restricted;

    [global::ProtoBuf.ProtoMember(16, Name = @"form_factor")]
    [global::System.ComponentModel.DefaultValue(EStreamDeviceFormFactor.kEStreamDeviceFormFactorUnknown)]
    public EStreamDeviceFormFactor FormFactor
    {
        get { return __pbn__FormFactor ?? EStreamDeviceFormFactor.kEStreamDeviceFormFactorUnknown; }
        set { __pbn__FormFactor = value; }
    }
    public bool ShouldSerializeFormFactor() => __pbn__FormFactor != null;
    public void ResetFormFactor() => __pbn__FormFactor = null;
    private EStreamDeviceFormFactor? __pbn__FormFactor;

    [global::ProtoBuf.ProtoMember(17, Name = @"gamepad_count")]
    public int GamepadCount
    {
        get { return __pbn__GamepadCount.GetValueOrDefault(); }
        set { __pbn__GamepadCount = value; }
    }
    public bool ShouldSerializeGamepadCount() => __pbn__GamepadCount != null;
    public void ResetGamepadCount() => __pbn__GamepadCount = null;
    private int? __pbn__GamepadCount;

    [global::ProtoBuf.ProtoMember(18, Name = @"gamepads")]
    public global::System.Collections.Generic.List<ReservedGamepad> Gamepads { get; } = new global::System.Collections.Generic.List<ReservedGamepad>();

    [global::ProtoBuf.ProtoMember(19, Name = @"gameid")]
    public ulong Gameid
    {
        get { return __pbn__Gameid.GetValueOrDefault(); }
        set { __pbn__Gameid = value; }
    }
    public bool ShouldSerializeGameid() => __pbn__Gameid != null;
    public void ResetGameid() => __pbn__Gameid = null;
    private ulong? __pbn__Gameid;

    [global::ProtoBuf.ProtoMember(20, Name = @"stream_interface")]
    [global::System.ComponentModel.DefaultValue(EStreamInterface.kEStreamInterfaceDefault)]
    public EStreamInterface StreamInterface
    {
        get { return __pbn__StreamInterface ?? EStreamInterface.kEStreamInterfaceDefault; }
        set { __pbn__StreamInterface = value; }
    }
    public bool ShouldSerializeStreamInterface() => __pbn__StreamInterface != null;
    public void ResetStreamInterface() => __pbn__StreamInterface = null;
    private EStreamInterface? __pbn__StreamInterface;

    [global::ProtoBuf.ProtoContract()]
    public partial class ReservedGamepad : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"controller_type")]
        public uint ControllerType
        {
            get { return __pbn__ControllerType.GetValueOrDefault(); }
            set { __pbn__ControllerType = value; }
        }
        public bool ShouldSerializeControllerType() => __pbn__ControllerType != null;
        public void ResetControllerType() => __pbn__ControllerType = null;
        private uint? __pbn__ControllerType;

        [global::ProtoBuf.ProtoMember(2, Name = @"controller_subtype")]
        public uint ControllerSubtype
        {
            get { return __pbn__ControllerSubtype.GetValueOrDefault(); }
            set { __pbn__ControllerSubtype = value; }
        }
        public bool ShouldSerializeControllerSubtype() => __pbn__ControllerSubtype != null;
        public void ResetControllerSubtype() => __pbn__ControllerSubtype = null;
        private uint? __pbn__ControllerSubtype;

    }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceStreamingCancelRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"request_id", IsRequired = true)]
    public uint RequestId { get; set; }

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceStreamingProgress : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"request_id", IsRequired = true)]
    public uint RequestId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"progress")]
    public float Progress
    {
        get { return __pbn__Progress.GetValueOrDefault(); }
        set { __pbn__Progress = value; }
    }
    public bool ShouldSerializeProgress() => __pbn__Progress != null;
    public void ResetProgress() => __pbn__Progress = null;
    private float? __pbn__Progress;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceStreamingResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"request_id", IsRequired = true)]
    public uint RequestId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"result", IsRequired = true)]
    public ERemoteDeviceStreamingResult Result { get; set; } = ERemoteDeviceStreamingResult.kERemoteDeviceStreamingSuccess;

    [global::ProtoBuf.ProtoMember(3, Name = @"port")]
    public uint Port
    {
        get { return __pbn__Port.GetValueOrDefault(); }
        set { __pbn__Port = value; }
    }
    public bool ShouldSerializePort() => __pbn__Port != null;
    public void ResetPort() => __pbn__Port = null;
    private uint? __pbn__Port;

    [global::ProtoBuf.ProtoMember(4, Name = @"encrypted_session_key")]
    public byte[] EncryptedSessionKey
    {
        get { return __pbn__EncryptedSessionKey; }
        set { __pbn__EncryptedSessionKey = value; }
    }
    public bool ShouldSerializeEncryptedSessionKey() => __pbn__EncryptedSessionKey != null;
    public void ResetEncryptedSessionKey() => __pbn__EncryptedSessionKey = null;
    private byte[] __pbn__EncryptedSessionKey;

    [global::ProtoBuf.ProtoMember(6, Name = @"transport")]
    [global::System.ComponentModel.DefaultValue(EStreamTransport.kEStreamTransportUDP)]
    public EStreamTransport Transport
    {
        get { return __pbn__Transport ?? EStreamTransport.kEStreamTransportUDP; }
        set { __pbn__Transport = value; }
    }
    public bool ShouldSerializeTransport() => __pbn__Transport != null;
    public void ResetTransport() => __pbn__Transport = null;
    private EStreamTransport? __pbn__Transport;

    [global::ProtoBuf.ProtoMember(7, Name = @"relay_server")]
    [global::System.ComponentModel.DefaultValue("")]
    public string RelayServer
    {
        get { return __pbn__RelayServer ?? ""; }
        set { __pbn__RelayServer = value; }
    }
    public bool ShouldSerializeRelayServer() => __pbn__RelayServer != null;
    public void ResetRelayServer() => __pbn__RelayServer = null;
    private string __pbn__RelayServer;

    [global::ProtoBuf.ProtoMember(8, Name = @"cert")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Cert
    {
        get { return __pbn__Cert ?? ""; }
        set { __pbn__Cert = value; }
    }
    public bool ShouldSerializeCert() => __pbn__Cert != null;
    public void ResetCert() => __pbn__Cert = null;
    private string __pbn__Cert;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceProofRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"challenge", IsRequired = true)]
    public byte[] Challenge { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
    public uint RequestId
    {
        get { return __pbn__RequestId.GetValueOrDefault(); }
        set { __pbn__RequestId = value; }
    }
    public bool ShouldSerializeRequestId() => __pbn__RequestId != null;
    public void ResetRequestId() => __pbn__RequestId = null;
    private uint? __pbn__RequestId;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceProofResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"response", IsRequired = true)]
    public byte[] Response { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"request_id")]
    public uint RequestId
    {
        get { return __pbn__RequestId.GetValueOrDefault(); }
        set { __pbn__RequestId = value; }
    }
    public bool ShouldSerializeRequestId() => __pbn__RequestId != null;
    public void ResetRequestId() => __pbn__RequestId = null;
    private uint? __pbn__RequestId;

}

[global::ProtoBuf.ProtoContract()]
public partial class CMsgRemoteDeviceStreamTransportSignal : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"token")]
    public byte[] Token
    {
        get { return __pbn__Token; }
        set { __pbn__Token = value; }
    }
    public bool ShouldSerializeToken() => __pbn__Token != null;
    public void ResetToken() => __pbn__Token = null;
    private byte[] __pbn__Token;

    [global::ProtoBuf.ProtoMember(2, Name = @"payload")]
    public byte[] Payload
    {
        get { return __pbn__Payload; }
        set { __pbn__Payload = value; }
    }
    public bool ShouldSerializePayload() => __pbn__Payload != null;
    public void ResetPayload() => __pbn__Payload = null;
    private byte[] __pbn__Payload;

}

[global::ProtoBuf.ProtoContract()]
public enum ERemoteClientBroadcastMsg
{
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientBroadcastMsgDiscovery")]
    kERemoteClientBroadcastMsgDiscovery = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientBroadcastMsgStatus")]
    kERemoteClientBroadcastMsgStatus = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientBroadcastMsgOffline")]
    kERemoteClientBroadcastMsgOffline = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationRequest")]
    kERemoteDeviceAuthorizationRequest = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationResponse")]
    kERemoteDeviceAuthorizationResponse = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingRequest")]
    kERemoteDeviceStreamingRequest = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingResponse")]
    kERemoteDeviceStreamingResponse = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceProofRequest")]
    kERemoteDeviceProofRequest = 7,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceProofResponse")]
    kERemoteDeviceProofResponse = 8,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationCancelRequest")]
    kERemoteDeviceAuthorizationCancelRequest = 9,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingCancelRequest")]
    kERemoteDeviceStreamingCancelRequest = 10,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientBroadcastMsgClientIDDeconflict")]
    kERemoteClientBroadcastMsgClientIDDeconflict = 11,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamTransportSignal")]
    kERemoteDeviceStreamTransportSignal = 12,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingProgress")]
    kERemoteDeviceStreamingProgress = 13,
}

[global::ProtoBuf.ProtoContract()]
public enum ERemoteClientService
{
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientServiceNone")]
    kERemoteClientServiceNone = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientServiceRemoteControl")]
    kERemoteClientServiceRemoteControl = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientServiceGameStreaming")]
    kERemoteClientServiceGameStreaming = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientServiceSiteLicense")]
    kERemoteClientServiceSiteLicense = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteClientServiceContentCache")]
    kERemoteClientServiceContentCache = 8,
}

[global::ProtoBuf.ProtoContract()]
public enum ERemoteDeviceAuthorizationResult
{
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationSuccess")]
    kERemoteDeviceAuthorizationSuccess = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationDenied")]
    kERemoteDeviceAuthorizationDenied = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationNotLoggedIn")]
    kERemoteDeviceAuthorizationNotLoggedIn = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationOffline")]
    kERemoteDeviceAuthorizationOffline = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationBusy")]
    kERemoteDeviceAuthorizationBusy = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationInProgress")]
    kERemoteDeviceAuthorizationInProgress = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationTimedOut")]
    kERemoteDeviceAuthorizationTimedOut = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationFailed")]
    kERemoteDeviceAuthorizationFailed = 7,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceAuthorizationCanceled")]
    kERemoteDeviceAuthorizationCanceled = 8,
}

[global::ProtoBuf.ProtoContract()]
public enum EStreamDeviceFormFactor
{
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamDeviceFormFactorUnknown")]
    kEStreamDeviceFormFactorUnknown = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamDeviceFormFactorPhone")]
    kEStreamDeviceFormFactorPhone = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamDeviceFormFactorTablet")]
    kEStreamDeviceFormFactorTablet = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamDeviceFormFactorComputer")]
    kEStreamDeviceFormFactorComputer = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamDeviceFormFactorTV")]
    kEStreamDeviceFormFactorTV = 4,
}

[global::ProtoBuf.ProtoContract()]
public enum EStreamTransport
{
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamTransportNone")]
    kEStreamTransportNone = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamTransportUDP")]
    kEStreamTransportUDP = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamTransportUDPRelay")]
    kEStreamTransportUDPRelay = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamTransportWebRTC")]
    kEStreamTransportWebRTC = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamTransportSDR")]
    kEStreamTransportSDR = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamTransportUDP_SNS")]
    kEStreamTransportUDPSNS = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamTransportUDPRelay_SNS")]
    kEStreamTransportUDPRelaySNS = 6,
}

[global::ProtoBuf.ProtoContract()]
public enum EStreamInterface
{
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamInterfaceDefault")]
    kEStreamInterfaceDefault = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamInterfaceRecentGames")]
    kEStreamInterfaceRecentGames = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamInterfaceBigPicture")]
    kEStreamInterfaceBigPicture = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"k_EStreamInterfaceDesktop")]
    kEStreamInterfaceDesktop = 3,
}

[global::ProtoBuf.ProtoContract()]
public enum ERemoteDeviceStreamingResult
{
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingSuccess")]
    kERemoteDeviceStreamingSuccess = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingUnauthorized")]
    kERemoteDeviceStreamingUnauthorized = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingScreenLocked")]
    kERemoteDeviceStreamingScreenLocked = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingFailed")]
    kERemoteDeviceStreamingFailed = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingBusy")]
    kERemoteDeviceStreamingBusy = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingInProgress")]
    kERemoteDeviceStreamingInProgress = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingCanceled")]
    kERemoteDeviceStreamingCanceled = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingDriversNotInstalled")]
    kERemoteDeviceStreamingDriversNotInstalled = 7,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingDisabled")]
    kERemoteDeviceStreamingDisabled = 8,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingBroadcastingActive")]
    kERemoteDeviceStreamingBroadcastingActive = 9,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingVRActive")]
    kERemoteDeviceStreamingVRActive = 10,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingPINRequired")]
    kERemoteDeviceStreamingPINRequired = 11,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingTransportUnavailable")]
    kERemoteDeviceStreamingTransportUnavailable = 12,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingInvisible")]
    kERemoteDeviceStreamingInvisible = 13,
    [global::ProtoBuf.ProtoEnum(Name = @"k_ERemoteDeviceStreamingGameLaunchFailed")]
    kERemoteDeviceStreamingGameLaunchFailed = 14,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
